// SPDX-FileCopyrightText: 2021 The Go Darwin Authors
// SPDX-License-Identifier: BSD-3-Clause

//go:build darwin && amd64 && gc
// +build darwin,amd64,gc

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -srcdir . -godefs /Users/zchee/go/src/github.com/go-darwin/libproc/file_info_darwin_amd64.go

package libproc

type ProcFDType uint32

const (
	ProxFDTypeAtalk     ProcFDType = 0x0
	ProxFDTypeVnode     ProcFDType = 0x1
	ProxFDTypeSocket    ProcFDType = 0x2
	ProxFDTypePshm      ProcFDType = 0x3
	ProxFDTypePsem      ProcFDType = 0x4
	ProxFDTypeKqueue    ProcFDType = 0x5
	ProxFDTypePipe      ProcFDType = 0x6
	ProxFDTypeFsevents  ProcFDType = 0x7
	ProxFDTypeNetpolicy ProcFDType = 0x9
)
