// SPDX-FileCopyrightText: 2021 The Go Darwin Authors
// SPDX-License-Identifier: BSD-3-Clause

//go:build darwin && amd64 && gc
// +build darwin,amd64,gc

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -srcdir . -godefs /Users/zchee/go/src/github.com/go-darwin/libproc/kmesg_buffer_darwin_amd64.go

package libproc

const (
	MaxMsgBSize = 0x100000
)
