// SPDX-FileCopyrightText: 2021 The Go Darwin Authors
// SPDX-License-Identifier: BSD-3-Clause

//go:build darwin && amd64 && gc
// +build darwin,amd64,gc

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs /Users/zchee/go/src/go-darwin.dev/libproc/net_info_darwin_amd64.go

package libproc

type SocketFDinfo struct {
	Pfi ProcFileinfo
	Psi SocketInfo
}

type ProcFileinfo struct {
	Openflags  uint32
	Status     uint32
	Offset     int64
	Type       int32
	Guardflags uint32
}

const (
	SockinfoGeneric   = 0x0
	SockinfoIn        = 0x1
	SockinfoKernCtl   = 0x6
	SockinfoKernEvent = 0x5
	SockinfoNdrv      = 0x4
	SockinfoTCP       = 0x2
	SockinfoUn        = 0x3
	SockinfoVsock     = 0x7
)

type SocketInfo struct {
	Soi_stat     VInfoStat
	Soi_so       uint64
	Soi_pcb      uint64
	Soi_type     int32
	Soi_protocol int32
	Soi_family   int32
	Soi_options  int16
	Soi_linger   int16
	Soi_state    int16
	Soi_qlen     int16
	Soi_incqlen  int16
	Soi_qlimit   int16
	Soi_timeo    int16
	Soi_error    uint16
	Soi_oobmark  uint32
	Soi_rcv      SockbufInfo
	Soi_snd      SockbufInfo
	Soi_kind     int32
	Rfu_1        uint32
	Soi_proto    [528]byte
}

type VInfoStat struct {
	Dev           uint32
	Mode          uint16
	Nlink         uint16
	Ino           uint64
	Uid           uint32
	Gid           uint32
	Atime         int64
	Atimensec     int64
	Mtime         int64
	Mtimensec     int64
	Ctime         int64
	Ctimensec     int64
	Birthtime     int64
	Birthtimensec int64
	Size          int64
	Blocks        int64
	Blksize       int32
	Flags         uint32
	Gen           uint32
	Rdev          uint32
	Qspare        [2]int64
}

type SockbufInfo struct {
	Cc    uint32
	Hiwat uint32
	Mbcnt uint32
	Mbmax uint32
	Lowat uint32
	Flags int16
	Timeo int16
}

type SockProto struct {
	Family   uint16
	Protocol uint16
}

type In4In6Addr struct {
	Pad32 [3]uint32
	Addr4 [4]byte // in_addr
}

type InSockinfo struct {
	Insi_fport  int32
	Insi_lport  int32
	Insi_gencnt uint64
	Insi_flags  uint32
	Insi_flow   uint32
	Insi_vflag  uint8
	Insi_ip_ttl uint8
	Rfu_1       uint32
	Insi_faddr  [16]byte
	Insi_laddr  [16]byte
	Insi_v4     InsiV4 // insi_v4
	Insi_v6     InsiV6 // insi_v6
}

type InsiV4 struct {
	Tos uint8
}

type InsiV6 struct {
	Hlim    uint8
	Cksum   int32
	Ifindex uint16
	Hops    int16
}

type InsiLaddr [16]byte

type TCPSIState int32

const (
	TSI_S_CLOSED       TCPSIState = 0x0
	TSI_S_LISTEN       TCPSIState = 0x1
	TSI_S_SYN_SENT     TCPSIState = 0x2
	TSI_S_SYN_RECEIVED TCPSIState = 0x3
	TSI_S_ESTABLISHED  TCPSIState = 0x4
	TSI_S__CLOSE_WAIT  TCPSIState = 0x5
	TSI_S_FIN_WAIT_1   TCPSIState = 0x6
	TSI_S_CLOSING      TCPSIState = 0x7
	TSI_S_LAST_ACK     TCPSIState = 0x8
	TSI_S_FIN_WAIT_2   TCPSIState = 0x9
	TSI_S_TIME_WAIT    TCPSIState = 0xa
	TSI_S_RESERVED     TCPSIState = 0xb
)

type TCPSockinfo struct {
	Tcpsi_ini   InSockinfo
	Tcpsi_state int32
	Tcpsi_timer [4]int32
	Tcpsi_mss   int32
	Tcpsi_flags uint32
	Rfu_1       uint32
	Tcpsi_tp    uint64
}

type UnSocinfo struct {
	Conn_so   uint64
	Conn_pcb  uint64
	Addr      [255]byte
	Caddr     [255]byte
	Pad_cgo_0 [2]byte
}

type NdrvInfo struct {
	If_family uint32
	If_unit   uint32
	If_name   [16]int8
}

type KernEventInfo struct {
	Vendor_code_filter uint32
	Class_filter       uint32
	Subclass_filter    uint32
}

type KernCTLInfo struct {
	Id          uint32
	Reg_unit    uint32
	Flags       uint32
	Recvbufsize uint32
	Sendbufsize uint32
	Unit        uint32
	Name        [96]int8
}

type VsockSockinfo struct {
	Local_cid   uint32
	Local_port  uint32
	Remote_cid  uint32
	Remote_port uint32
}
